### ISSUE TITLE
Only one trash in sensor.trash_tomorrow and sensor.trash_today

### ISSUE THREAD

**Issue by jantje88** [xirixiz/home-assistant-config#3]
I like the sensor.trash_tomorrow and sensor.trash_today sensors, but only one trash is shown in the sensor.
Any change to show all of the trashes which will be picked up tomorrow or today?

![](https://i.imgur.com/SxLryJV.png)

**Comment by xirixiz** [comment]
I think the custom_component did a good job by selecting the most important garbage...luiers :).

This feature has been requested more often, but unfortunately I don't have duplicate garbage pickups on one day. Perhaps you could provide me your postal code? I'll pick a random housenumber to test with, but that's the only way I can look into this. 

Cheers

**Comment by jantje88** [comment]
> I think the custom_component did a good job by selecting the most important garbage...luiers :).
> 
> This feature has been requested more often, but unfortunately I don't have duplicate garbage pickups on one day. Perhaps you could provide me your postal code? I'll pick a random housenumber to test with, but that's the only way I can look into this.
> 
> Cheers

Haha, you are right :-)
You can test with postal code 5685 HE (not mine, just random with multiple pickups at one day).

**Comment by xirixiz** [comment]
Hi Jantje,

Good to hear. I just released version 1.1.5 with comma seperated items. Friendly names is impossible due to the different naming the mijnafvalwijzer website uses. Etensresten in mij region is called gft, which also includes tuinafval. Restafval is also named different. I guess it depends how your "gemeente" provides the information to mijnafvalwijzer. However, you could create a template sensor ofcourse and add the items you'd like to provide a friendly name.

Cheers.

**Comment by Sholofly** [comment]
Hi Bram,

Sorry for the delayed response. The feature is brilliant. Thanks!
